### ISSUE TITLE
Allowing the @ symbols in the username

### ISSUE THREAD

**Issue by dallen66** [vitaly-t/connection-string#15]
Azure SQL sometime have the @ symbol in the username. Parsing fail if I include the @.
`mssql://username@servername:password@servername.database.windows.net/database?encrypt=true`

Thanks

**Comment by vitaly-t** [comment]
As per the spec, the user name must be URL-encoded, and `@` must be `%40`.

**Comment by dallen66** [comment]
Ok Thank

**Comment by vitaly-t** [comment]
And if you are providing the password dynamically, the easiest approach is to simply encode it:

```js
const encodedPassword = encodeURIComponent(password);
```

**Comment by vitaly-t** [comment]
Added in **FAQ -** [How to use special symbols for user name or password?](https://github.com/vitaly-t/connection-string/wiki/FAQ#how-to-use-special-symbols-for-user-name-or-password)
