### ISSUE TITLE
Parsing for multihost

### ISSUE THREAD

**Issue by kalemayur8** [vitaly-t/connection-string#29]
Hi There, 

I was trying to parse the below URL , but it is returning null 

`const h = ConnectionString.parseHost('[server.site1.company.com::]:1512);
console.log(h);`

prints null on console.

Basically I want to create multihost string like below 

`postgres://user:password@server1.site1.company.com:1512,[server2.site2.company.com::]:1512/dbname?target_session_attrs=read-write
`

**Comment by vitaly-t** [comment]
What is `[server.site1.company.com::]`? That's not a valid address at all.

**Comment by kalemayur8** [comment]
@vitaly-t  any suggestion on how it should be with domain name?

**Comment by vitaly-t** [comment]
> but while trying to connect with DB fails here

Why your database server does not recognize a connection - probably because it does not support multi-host configurations. But that's not relevant for investigation here. That's the driver's issue.

**Comment by vitaly-t** [comment]
As far as `Parsing for multi-host` goes here, I believe this has been sorted, so I am closing the issue.
