### ISSUE TITLE
Allow specifying default hostname and port separately

### ISSUE THREAD

**Issue by mariusmarais** [vitaly-t/connection-string#36]
I would like to specify the default hostname and default port as separate fields, and not together as an `IHost`.

As is typical of at least WWW URLs, I expect to be able to omit the port from the input connection string, resulting in the default value to be used, but this isn't what is happening.  Although less common, for the same reason I expect a blank host name to be defaulted too.

Full example (these are RabbitMQ defaults FWIW):
```js
const { ConnectionString, HostType } = require('connection-string');

function example(connStr) {
    return (new ConnectionString(connStr, {
    protocol: 'amqp',
    user: 'guest',
    password: 'guest',
    hosts: [{ name: 'localhost', port: 5672, type: HostType.domain }],
    path: ['vhost1'],
    params: { heartbeat: 60 }
  })).toString();
}

console.log('1:', example(''));
// => 1: amqp://guest:guest@localhost:5672/vhost1?heartbeat=60
// correct :)

console.log('2:', example('amqp://localhost:5672'));
// => 2: amqp://guest:guest@localhost:5672/vhost1?heartbeat=60
// correct, same as 1

console.log('3:', example('amqp://localhost'));
// => 3: amqp://guest:guest@localhost,localhost:5672/vhost1?heartbeat=60
// incorrect, expecting same as 1 & 2

console.log('4:', example('amqp://localhost:1234'));
// => 4: amqp://guest:guest@localhost:1234,localhost:5672/vhost1?heartbeat=60
// incorrect, expecting amqp://guest:guest@localhost:1234/vhost1?heartbeat=60
```

To keep backwards compatibility, I propose that the `IConnectionDefaults` be extended with `port` and `hostname` (naming?) fields, which apply when no port or hostname is specified in the connection string. Anyone using default `IHost`s can continue to do so, although I doubt it is usable given the current quirks.

**Comment by mariusmarais** [comment]
I've created a messy workaround for my use case, which may be a starting point for a feature, but I'm unsure of all the edge cases.

```ts
function createCSFactory({port, hostname, ...defaults}: Omit<IConnectionDefaults, "hosts"> & 
  { port?: number, hostname?: string}) {

  return (connStr: string) => {
    const cs = new ConnectionString(connStr, defaults);

    if (!cs.hosts || cs.hosts.length === 0) {
        const defaultPair = ConnectionString.parseHost(`${hostname}:${port}`);
        if (defaultPair) {
          cs.hosts = [defaultPair];
        }
      } else {
        cs.hosts.forEach((host, i) => {
          let update: IParsedHost | null = null;

          if (host.name && !host.port) {
            // just update port
            host.port = defaultPort;
          } else {
            // must re-parse to set type
            update = ConnectionString.parseHost(`${defaultHostname}:${host.port || defaultPort}`);
          }

          if (update) {
            cs.hosts![i] = update;
          }
        });
      }
  }

  return cs;
}
```

This is then used like so (there's also some SRV lookups and so-on on my side, but not relevant to this issue):

```ts
export function createRabbitMqConnStrParser() {
  return createCSFactory({
      protocol: 'amqp',
      user: 'guest',
      password: 'guest',
      hostname: 'localhost',
      port: 5672,
      path: ['/'], // yes, this is correct, the default vhost is called '/'
      params: { heartbeat: 60 }
  });
}
```

**Comment by vitaly-t** [comment]
When you specify `localhost`, `localhost:1234` and `localhost:5672`, those are all different servers, so joining them is the correct logic, and I do not see how it is incorrect.

**Comment by vitaly-t** [comment]
Here's by the way, a typical use case - [connection-string-demo](https://github.com/vitaly-t/connection-string-demo).

**Comment by vitaly-t** [comment]
If we consider adding `port` into `IConnectionDefaults`, to be auto-applied to every host that doesn't have port specified, then I'm not sure that adding it to socket-type addresses will be a good idea.

And adding `hostname` to `IConnectionDefaults` would be redundant, because you already can add a list of default hosts, and if default port is applied, it would be added (pending the above is implemented).

**Comment by mariusmarais** [comment]
Agreed, you could ignore a default port for a UNIX socket, since it doesn't make sense there.

But I still don't see a way to use a default hostname or port of them isn't specified. I don't understand in which scenarios someone would always want to ADD another host to a URI instead of only as a default.

Like for instance, if I want to go to a search engine, using Google by default would be fine if I don't specify what to use. But the lib current says that if I ask for Bing, it's going to use Google AS WELL instead of just as a default.  It's no longer a default, it's mandatory.  (Also, a default protocol doesn't add to the user-supplied protocol.)

If that is your intention, maybe the naming can be improved, since `default` implies different semantics, at least to me.

**Comment by vitaly-t** [comment]
Default port is set either by the client library or the hosting environment, or both. Use of a default port through the connection string doesn't add much value. For example, if you use `node-postgres` driver, it will use 5432 as the default port, from the client itself.

> Also, a default protocol doesn't add to the user-supplied protocol

I'm not sure what you mean. Are you saying that default for the protocol doesn't work?

**Comment by mariusmarais** [comment]
I think I didn't explain myself well.  I'm using connection-string to parse a user-supplied connection-string to connect to a RabbitMQ cluster, not to build connection strings for other libraries.  The mainstream amqplib client also does not support multiple connections, you do that yourself.

So for my use-case, I am the client library.

So I get a connection string from ENV, and then want to parse it with some defaults, such as the standard RabbitMQ port number, localhost default hostname and default credentials.  This is where I am struggling, because the connection-string "defaults" feature does not work in a way that lets me use it inside a client library.

What I mean by protocol is this: If I specify a "default protocol" of `abc`, and parse `xyz://` get `xyz://`, but if I parse a "default port" of `1234` and parse `http://localhost` I get `http://localhost,:1234`. I expect to get `xyz://localhost:1234`.

As I said earlier, I understand WHY (because a default port is actually a default host), but it limits the utility of the library and does not match the "default protocol" behaviour, which is as I expect it be.

Does that make sense?

**Comment by vitaly-t** [comment]
> But if I parse a "default port"...

There library doesn't have such thing as "default port", it only lets you specify port for a default host that you provide. That's why the expectation is incorrect.

**Comment by vitaly-t** [comment]
Later on, even created a branch and started adding support for default port, but dropped the idea, once I started figuring out all the logic of applying default port in various scenarios.

The last thing I want is to introduce something confusing, with convoluted logic. Right now the library has clear logic for applying all the defaults. And I intend to keep it that way.

Therefore, closing the issue.
