### ISSUE TITLE
Any interest in accepting an SRV lookups feature to the lib?

### ISSUE THREAD

**Issue by mariusmarais** [vitaly-t/connection-string#37]
If there is any interest, I'd like to contribute an SRV lookup feature to this library which I've been using successfully with Kubernetes Services, but I think is generally useful.

Essentially, if a `protocol` ends with `+srv`, such as in `amqp+srv://some.dns.name/path`, perform a DNS SRV lookup for actual hostnames and ports.

No additional dependencies past Node is necessary.

Any thoughts?

**Comment by vitaly-t** [comment]
Are you suggesting to add TCP communications into a URL parser?

**Comment by vitaly-t** [comment]
I don't know where that idea of using `+` inside protocol name came from, but it vailates general URL spec where each `+` is treated as a space, which is what this library does.

**Comment by mariusmarais** [comment]
The idea comes from MongoDB to simplify cluster configuration, and we're using it for RabbitMQ cluster configuration also with plans to use it for PostgreSQL. The idea works well for anything where you know the service you want, but not the exact set of hosts at config time.  Kubernetes Services are also exposed as SRV records out of the box.

See https://www.mongodb.com/blog/post/mongodb-3-6-here-to-SRV-you-with-easier-replica-set-connections (ignore the TXT record part).

In terms of spec, the `+` can decode to a space, it is just how how a user would specify the URI.

The idea is to transform a URI like `amqp+srv://service.dns.name/path` into `amqp://server1:9999,server2:8888/path` with the help of an SRV record (and UDP or TCP :smile:)

If you feel it will go out of scope for the library, that is understandable. That is why I asked instead of just blindly submitting a PR.

**Comment by vitaly-t** [comment]
> The idea comes from MongoDB to simplify cluster configuration

That's what I thought. Their implementation of URL connection string doesn't respect the standard, which has been discussed here in other issues already.

**Comment by mariusmarais** [comment]
OK, that makes sense, closing.

**Comment by vitaly-t** [comment]
Another wiki page added - [Compatibility](https://github.com/vitaly-t/connection-string/wiki/Compatibility).

**Comment by vitaly-t** [comment]
Released [v4.0.0](https://github.com/vitaly-t/connection-string/releases/tag/4.0.0), which now handles `+` correctly inside the protocol name.
