### ISSUE TITLE
Invalid URL character '~' 

### ISSUE THREAD

**Issue by peterp** [vitaly-t/connection-string#52]
In the documentation it states:
> Other special symbols, such as ~ or $, for example, can be, but do not need to be encoded.

However, `postgresql://postgres:pass~word@localhost:5432/postgres` receives the following error:
`Error: Invalid URL character '~' at position 26`

Is this a bug, or a misunderstanding?

**Comment by vitaly-t** [comment]
> Is this a bug, or a misunderstanding?

Possibly, a bug. A discrepancy for sure. This needs to be addressed. You can for now encode it as `%7E`.

**Comment by vitaly-t** [comment]
Fixed in [v4.3.6](https://github.com/vitaly-t/connection-string/releases/tag/4.3.6).
